# Generated by Django 5.0.6 on 2024-06-09 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=75)),
                ('department', models.CharField(max_length=75)),
                ('publications', models.PositiveIntegerField()),
                ('strict', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('skill', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('marks', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('fit', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('ap', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
